phrase = "Python Course"
print(phrase + " is cool")
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[7])
print(phrase.index("h"))
print(phrase.replace("Course", "is cool"))